### ISSUE TITLE
process_emu_fread does not check if fd corresponds to random device.

### ISSUE THREAD

**Issue by RWails** [shadow/shadow#368]
https://github.com/shadow/shadow/blob/4eb6066fa0b7cb0f802c5408349de43c69d058f0/src/main/host/shd-process.c#L4151

process_emu_fread should have behavior similar to process_emu_read; when the fd being read corresponds to one of the system's random devices, Shadow should intercept the read and instead provide its own randomness back to the host.

**Comment by robgjansen** [comment]
This was likely just overlooked whenever we started intercepting fread. I think we can just use the code from read, i.e.:

```
else if(host_isRandomHandle(proc->host, fd)) {
   Random* random = host_getRandom(proc->host);
   random_nextNBytes(random, (guchar*)buff, numbytes);
   ret = (ssize_t) numbytes;
}
```

with numbytes changed to the correct size value.

**Comment by robgjansen** [comment]
@RWails I think I fixed this in e7bcce8, but I didn't test this. Can you verify that this produces the expected result when using `fread` on random devices?

**Comment by RWails** [comment]
e7bcce8 does not seem to fix this issue...

I ran an experiment where I read() & fread() a byte from /dev/random and /dev/urandom.
Rerunning the experiment produces the same random bytes from read(), but not from fread().

My Shadow version is "Shadow v1.12.0-34-ge7bcce8 2017-11-30 (built 2017-12-04) running GLib v2.50.3 and IGraph v0.7.1".

Can provide code if that would help further

**Comment by robgjansen** [comment]
@RWails Your code would help. Seems simple enough that you could just paste it in a comment, but if I'm wrong feel free to email it to me instead.

**Comment by RWails** [comment]
```C
#define _POSIX_C_SOURCE 199309L
#include <assert.h>
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <sys/types.h>
#include <unistd.h>

static void test_open(const char *filename) {
   unsigned char buf[1];
   buf[0] = 0;

   int fd = open(filename, O_RDONLY);
   assert(fd > -1);

   ssize_t sz = read(fd, buf, 1);
   assert(sz == 1);

   printf("%s\t: %X\n", filename, *buf);
   close(fd);
}

static void test_fopen(const char *filename) {
   unsigned char buf[1];
   buf[0] = 0;

   FILE *fp = fopen(filename, "r");
   assert(fp != NULL);

   size_t sz = fread(buf, 1, 1, fp);
   assert(sz == 1);

   printf("%s\t: %X\n", filename, *buf);

   fclose(fp);
}

int main(int argc, char **argv) {

   test_open("/dev/random");
   test_open("/dev/urandom");

   test_fopen("/dev/random");
   test_fopen("/dev/urandom");

   return 0;

}
```

**Comment by robgjansen** [comment]
Thanks for the test code, @RWails!
